from typing import Self

from z3 import BoolRef, ExprRef, And, Implies, Or, Not, ForAll, If, Exists, EnumSort

from ranks import (
    ClosedRank,
    Rank,
    BinRank,
    PosInOrderRank,
    CondRank,
    DomainPointwiseRank,
    DomainLexRank,
    LexRank,
    PointwiseRank,
    DomainPermutedRank,
    FiniteLemma,
    TSRel,
)
from termination import (
    Proof,
    invariant,
    temporal_invariant,
    witness,
    temporal_witness,
    track,
)
from timers import (
    timer_zero,
    timer_finite,
    Time,
    timer_infinite,
    timer_nonzero,
    timer_decreasable,
)
from temporal import G, F, Prop
from ts import (
    TransitionSystem,
    Immutable,
    axiom,
    init,
    transition,
    ParamSpec,
    TSTerm,
    ts_term,
)
from typed_z3 import Expr, Rel, Fun, Finite, WFRel, Bool, Enum, false, true

__all__ = [
    "Self",
    "BoolRef",
    "ExprRef",
    "And",
    "Implies",
    "Or",
    "Not",
    "ForAll",
    "If",
    "Exists",
    "EnumSort",
    "ClosedRank",
    "Rank",
    "BinRank",
    "PosInOrderRank",
    "CondRank",
    "DomainPointwiseRank",
    "DomainLexRank",
    "LexRank",
    "PointwiseRank",
    "DomainPermutedRank",
    "FiniteLemma",
    "TSRel",
    "Proof",
    "invariant",
    "temporal_invariant",
    "witness",
    "temporal_witness",
    "track",
    "G",
    "F",
    "Prop",
    "timer_zero",
    "timer_finite",
    "Time",
    "timer_infinite",
    "timer_nonzero",
    "timer_decreasable",
    "TransitionSystem",
    "Immutable",
    "axiom",
    "init",
    "transition",
    "ParamSpec",
    "TSTerm",
    "ts_term",
    "Expr",
    "Rel",
    "Fun",
    "Finite",
    "WFRel",
    "Bool",
    "Enum",
    "false",
    "true",
]
